@startuml
'https://plantuml.com/sequence-diagram

'SEQUENCE DIAGRAM: PHASE 2

actor RestaurantSystem
participant OrderListener
participant OrderTrackerController
participant Parser
participant OrderDriver

RestaurantSystem -> OrderListener : New order files detected in testOrders folder
OrderListener -> OrderTrackerController : addOrderFile(file)
OrderTrackerController -> Parser : parseJSONOrder(file) [if JSON]
OrderTrackerController -> Parser : parseXMLOrder(file) [if XML]
Parser --> OrderTrackerController : Return Order
OrderTrackerController -> OrderDriver : addOrder(order)
OrderDriver --> OrderTrackerController : Return
OrderTrackerController -> OrderTrackerController : Update GUI

'OLD SEQUENCE DIAGRAM FROM PHASE 1

'actor RestaurantStaff
'participant SystemGUI
'participant ShowFileChooser
'participant Parser
'participant OrderDriver
'
'RestaurantStaff -> SystemGUI : Click "Import Order JSON" button
'SystemGUI -> ShowFileChooser : importOrder(parentFrame, driver)
'ShowFileChooser -> ShowFileChooser : Open file chooser
'RestaurantStaff -> ShowFileChooser : Select JSON file
'ShowFileChooser -> Parser : parseJSONOrder(file)
'Parser -> Parser : Create Order object from JSON
'Parser --> ShowFileChooser : Return Order
'ShowFileChooser -> OrderDriver : addOrder(order)
'OrderDriver --> ShowFileChooser : Confirmation
'ShowFileChooser --> SystemGUI : Show message "JSON imported into Order #ID"
'SystemGUI --> RestaurantStaff : Display confirmation
@enduml